### ISSUE TITLE
which is the vehicle detection neural network for jetson-tx2 and tensor-rt?

### ISSUE THREAD

**Issue by PiyalGeorge** [karolmajek/VehicleTracking#1]
Hi @karolmajek , With your practice and experience can you clear a simple doubt of mine? I'm trying to do vehicle detection with tensor-rt and jetson-tx2 board. I tried with mobilenet-ssd. its good and speed but not satisfied since it doesnt detect distant vehicles. so tried looking into Faster-RCNN but its not fast in jetson. now trying to look into yolov3 or yolov2(not tiny-yolo, since tiny is less accurate), but that too i think is not fast in jetson board. so Which is the best option you can give me?

**Comment by karolmajek** [comment]
I'm not an expert in embedded.
Jetson's are pretty slow compared to GPUs in laptops/PCs. 
If you can achieve good performance on big objects and really need small the best fit will be YOLOv3.
You can also try to zoom in or make 2 preds from one image with different zoom
Faster-RCNN Nasnet can give you nice results, but it's too big and too slow.
Consider moving to Xavier :-)
They gave you nice ideas there https://github.com/AlexeyAB/darknet/issues/2019
I don't have anything to add.

Is this a proper place for such question?

**Comment by PiyalGeorge** [comment]
this is fine, i'll look into those above. Thank you, @karolmajek . Thanks alot
